my-eks-1 test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -19,7 +19,7 @@ env:
   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
   BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
   AWS_REGION: us-east-2
-  EKS_CLUSTER_NAME: my-eks
+  EKS_CLUSTER_NAME: my-eks-1
 
 
 jobs:
@@ -54,23 +54,23 @@ jobs:
         run: terraform validate
 
 
-     # - name: "Terraform plan"
-      #  id: plan
-      #  run: terraform plan -no-color -input=false -out planfile.tfplan
-      #  continue-on-error: true
+      - name: "Terraform plan"
+        id: plan
+        run: terraform plan -no-color -input=false -out planfile.tfplan
+        continue-on-error: true
 
 
-     # - name: Terraform plan status
-     #   if: steps.plan.outcome == 'failure'
-     #   run: |
-     #     echo "Terraform plan failed. Please check the logs for details."
-     #     exit 1
+      - name: Terraform plan status
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "Terraform plan failed. Please check the logs for details."
+          exit 1
 
 
       - name: "Terraform apply"
         id: apple
-        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform destroy -auto-approve -input=false planfile.tfplan #-parallelism=1
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: terraform apply -auto-approve -input=false planfile.tfplan -parallelism=1
 
       - name: "configure aws credentials"
         uses: aws-actions/configure-aws-credentials@v1
@@ -86,7 +86,7 @@ jobs:
       
 
       - name: Install Ingress controller
-       # if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
+        if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
         run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
       
 #
