test 100

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -45,31 +45,31 @@ jobs:
         run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
 
-      - name: "Terraform format"
-        id: format
-        run: terraform fmt -check
+      #- name: "Terraform format"
+      #  id: format
+      #  run: terraform fmt -check
 
-      - name: "Terraform validate"
-        id: validate
-        run: terraform validate
-
-
-      - name: "Terraform plan"
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile.tfplan
-        continue-on-error: true
+      #- name: "Terraform validate"
+       # id: validate
+        #run: terraform validate
 
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: |
-          echo "Terraform plan failed. Please check the logs for details."
-          exit 1
+      #- name: "Terraform plan"
+        #id: plan
+        #run: terraform plan -no-color -input=false -out planfile.tfplan
+        #continue-on-error: true
+
+
+      #- name: Terraform plan status
+       # if: steps.plan.outcome == 'failure'
+        #run: |
+         # echo "Terraform plan failed. Please check the logs for details."
+          #exit 1
 
 
       - name: "Terraform apply"
         id: apple
-        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: terraform destroy -no-color -input=false -auto-approve -parallelism=1 #planfile.tfplan
 
 #      - name: "configure aws credentials"
