test 133

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -45,47 +45,47 @@ jobs:
         run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
 
-      #- name: "Terraform format"
-      #  id: format
-      #  run: terraform fmt -check
+      - name: "Terraform format"
+        id: format
+        run: terraform fmt -check
 
-      #- name: "Terraform validate"
-       # id: validate
-        #run: terraform validate
-
-
-      #- name: "Terraform plan"
-        #id: plan
-        #run: terraform plan -no-color -input=false -out planfile.tfplan
-        #continue-on-error: true
+      - name: "Terraform validate"
+        id: validate
+        run: terraform validate
 
 
-      #- name: Terraform plan status
-       # if: steps.plan.outcome == 'failure'
-        #run: |
-         # echo "Terraform plan failed. Please check the logs for details."
-          #exit 1
+      - name: "Terraform plan"
+        id: plan
+        run: terraform plan -no-color -input=false -out planfile.tfplan
+        continue-on-error: true
+
+
+      - name: Terraform plan status
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "Terraform plan failed. Please check the logs for details."
+          exit 1
 
 
       - name: "Terraform apply"
         id: apple
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform destroy -auto-approve #planfile.tfplan
+        run: terraform apply -auto-approve -input=false -parallelism=1 planfile.tfplan
 
-#      - name: "configure aws credentials"
-#        uses: aws-actions/configure-aws-credentials@v1
-#        with:
-#            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#            aws-region: ${{ env.AWS_REGION }}
-#    
-#      - name: "Configure kubectl"
-#        id: getconfig
-#        if: steps.apple.outcome == 'success'
-#        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
-#      
-#
-#      - name: Install Ingress controller
-#        if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
-#        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+      - name: "configure aws credentials"
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws-region: ${{ env.AWS_REGION }}
+    
+      - name: "Configure kubectl"
+        id: getconfig
+        if: steps.apple.outcome == 'success'
+        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
+      
+
+      - name: Install Ingress controller
+        if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
+        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
       
